In [1]:
import requests
page3=requests.get('https://www.news18.com/cricketnext/news/ipl-auction-2016-all-you-need-to-know-about-the-351-player-cricket-market-1199280.html')
page3

In [2]:
from bs4 import BeautifulSoup
soup3 = BeautifulSoup(page3.content, 'html.parser')
#print(soup3.prettify())

In [3]:
table=soup3.find_all('table',class_='tg')
pname=[]
ptype=[]
pbase=[]
for i in range(1,6):
    for row in table[i].findAll('tr'):
        if(row.findAll('td')):
            name=row.findAll('td')
            pname.append(name[0].get_text().strip())
            ptype.append(name[1].get_text().strip())
            pbase.append(name[2].get_text().strip().replace('â‚¹',''))
print(pbase)
print(len(pbase))

['2,00,00,000', '2,00,00,000', '2,00,00,000', '2,00,00,000', '1,50,00,000', '1,00,00,000', '50,00,000', '50,00,000', '2,00,00,000', '1,50,00,000', '1,50,00,000', '1,00,00,000', '1,00,00,000', '1,00,00,000', '1,00,00,000', '1,00,00,000', '1,00,00,000', '1,00,00,000', '1,00,00,000', '50,00,000', '50,00,000', '50,00,000', '50,00,000', '50,00,000', '50,00,000', '50,00,000', '50,00,000', '30,00,000', '30,00,000', '30,00,000', '30,00,000', '30,00,000', '30,00,000', '30,00,000', '30,00,000', '20,00,000', '20,00,000', '20,00,000', '20,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '2,00,00,000', '2,00,00,000', '2,00,00,000', '1,50,00,000', '1,50,00,000', '1,00,00,000', '1,00,00,000', '1,00,00,000', '1,00,00,000', '1,00,00,000', '50,00,000', '50,00,000', '50,00,000', '50,00,000', '50,00,000', '50,00,000', '50,00,000', '50,00,000', '50,00,000', '50,00,000', '50,00,000', '50,00,000', '50,00,000', '50,00,000', '50,00,000', '50,00,000', '30,00,000', '30,00,000', '30,00,000', '30,00,000', '30,00,000', '30,00,000', '30,00,000', '30,00,000', '30,00,000', '30,00,000', '30,00,000', '30,00,000', '30,00,000', '30,00,000', '30,00,000', '30,00,000', '30,00,000', '30,00,000', '30,00,000', '30,00,000', '30,00,000', '20,00,000', '20,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '2,00,00,000', '2,00,00,000', '1,50,00,000', '1,50,00,000', '30,00,000', '30,00,000', '30,00,000', '30,00,000', '30,00,000', '30,00,000', '30,00,000', '30,00,000', '20,00,000', '20,00,000', '20,00,000', '20,00,000', '20,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '2,00,00,000', '2,00,00,000', '1,50,00,000', '1,00,00,000', '1,00,00,000', '1,00,00,000', '1,00,00,000', '1,00,00,000', '50,00,000', '50,00,000', '50,00,000', '50,00,000', '50,00,000', '50,00,000', '50,00,000', '50,00,000', '50,00,000', '50,00,000', '50,00,000', '50,00,000', '50,00,000', '50,00,000', '50,00,000', '30,00,000', '30,00,000', '30,00,000', '30,00,000', '30,00,000', '30,00,000', '30,00,000', '30,00,000', '30,00,000', '30,00,000', '30,00,000', '30,00,000', '30,00,000', '30,00,000', '30,00,000', '30,00,000', '30,00,000', '30,00,000', '30,00,000', '30,00,000', '30,00,000', '30,00,000', '30,00,000', '30,00,000', '30,00,000', '30,00,000', '20,00,000', '20,00,000', '20,00,000', '20,00,000', '20,00,000', '20,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000', '10,00,000']
351

In [4]:
import pandas as pd
df16=pd.DataFrame()
df16['Player Name']=pname
df16['Role']=ptype
df16['Base Price']=pbase
df16

                 Player Name         Role   Base Price
0              Ishant Sharma       Bowler  2,00,00,000
1               Shane Watson  All-Rounder  2,00,00,000
2            Kevin Pietersen      Batsman  2,00,00,000
3               Yuvraj Singh  All-Rounder  2,00,00,000
4                 Dale Steyn       Bowler  1,50,00,000
5                Aaron Finch      Batsman  1,00,00,000
6             Martin Guptill      Batsman    50,00,000
7               Dwayne Smith  All-Rounder    50,00,000
8             Michael Hussey      Batsman  2,00,00,000
9              Cameron White      Batsman  1,50,00,000
10        Mahela Jayawardena      Batsman  1,50,00,000
11              David Hussey      Batsman  1,00,00,000
12             Usman Khawaja      Batsman  1,00,00,000
13                Owais Shah      Batsman  1,00,00,000
14                Adam Voges      Batsman  1,00,00,000
15               Hashim Amla      Batsman  1,00,00,000
16             Rilee Rossouw      Batsman  1,00,00,000
17                 Joe Burns      Batsman  1,00,00,000
18             George Bailey      Batsman  1,00,00,000
19     Subramaniam Badrinath      Batsman    50,00,000
20               Tamim Iqbal      Batsman    50,00,000
21            Marlon Samuels      Batsman    50,00,000
22              Richard Levi      Batsman    50,00,000
23              Darren Bravo      Batsman    50,00,000
24             Nic Maddinson      Batsman    50,00,000
25                Brad Hodge      Batsman    50,00,000
26         Cheteshwar Pujara      Batsman    50,00,000
27           Michael Klinger      Batsman    30,00,000
28            Aiden Blizzard      Batsman    30,00,000
29            Abhinav Mukund      Batsman    30,00,000
..                       ...          ...          ...
321           Mayank Siddana  All-Rounder    10,00,000
322            Shasank Singh  All-Rounder    10,00,000
323        Chandra Pal Singh  All-Rounder    10,00,000
324            Tanveer Ulhaq  All-Rounder    10,00,000
325           Iqbal Abdullah  All-Rounder    10,00,000
326          Shubham Ranjane  All-Rounder    10,00,000
327   Akhil Arvind Herwadkar  All-Rounder    10,00,000
328            Ashok Menaria  All-Rounder    10,00,000
329             Yogesh Nagar  All-Rounder    10,00,000
330             Milind Kumar  All-Rounder    10,00,000
331            Akshdeep Nath  All-Rounder    10,00,000
332             Sumit Narwal  All-Rounder    10,00,000
333         Biplab Samantray  All-Rounder    10,00,000
334             Rush Kalaria  All-Rounder    10,00,000
335             Jalaj Saxena  All-Rounder    10,00,000
336            Vijay Shankar  All-Rounder    10,00,000
337     Raiphi Vincent Gomez  All-Rounder    10,00,000
338            Kuldeep Hooda  All-Rounder    10,00,000
339            Vaibhav Rawal  All-Rounder    10,00,000
340     Prasanth Padmanabhan  All-Rounder    10,00,000
341       Jaydev Gokul Bista  All-Rounder    10,00,000
342    Ankit Nagendra Sharma  All-Rounder    10,00,000
343           Kshitiz Sharma  All-Rounder    10,00,000
344            Swapnil Singh  All-Rounder    10,00,000
345          Shrikant Mundhe  All-Rounder    10,00,000
346            Abhishek Raut  All-Rounder    10,00,000
347               Rohan Prem  All-Rounder    10,00,000
348  Manjeet Kumar Chaudhary  All-Rounder    10,00,000
349            Rahul Tewatia  All-Rounder    10,00,000
350               Amit Yadav  All-Rounder    10,00,000

[351 rows x 3 columns]

In [5]:
import requests

page1 = requests.get("https://www.iplt20.com/stats/2016/player-points")
page1

In [6]:
from bs4 import BeautifulSoup
soup1 = BeautifulSoup(page1.content, 'html.parser')

In [7]:
sb=[]
#sb1=[]
#name=row.findAll('a')lname=row.findAll('span',class_='top-players__last-name')
fours=[]
sixes=[]
wickets=[]
for i in range(0,159):
    sb.append(float(soup1.find_all('td',class_='top-players__pts top-players__padded is-active')[i].get_text().lstrip().rstrip()))
print(len(sb))
for i in range(0,159):
    sixes.append(soup1.find_all('td',class_='top-players__6s')[i].get_text().lstrip().rstrip())
    fours.append(soup1.find_all('td',class_='top-players__4s')[i].get_text().lstrip().rstrip())
    wickets.append(soup1.find_all('td',class_='top-players__w')[i].get_text().lstrip().rstrip())
print(len(fours))

159
159

In [8]:
table=soup1.find('table',class_='top-players')
sb1=[]
for row in table.find_all('tr'):
    name=row.findAll('a')
    if len(name)==1:
        sb1.append((name[0].get_text().strip().replace(' ','').replace('\n',' ')))
    else:
        if row.findAll('div',class_='top-players__player-name'):
            name1=row.findAll('div',class_='top-players__player-name')
            sb1.append((name1[0].get_text().strip().replace(' ','').replace('\n',' ')))
len(sb1)

159

In [9]:
import pandas as pd1
df1=pd1.DataFrame(sb,columns=['points'])
df1['Player Name']=sb1
df1['4s']=fours
df1['6s']=sixes
df1['Wkts']=wickets
df1

     points           Player Name  4s  6s Wkts
0     356.5           Virat Kohli  83  38    0
1     338.5          David Warner  88  31    0
2     319.5         AB deVilliers  57  37    0
3     283.0          Shane Watson  14  12   20
4     270.0     Bhuvneshwar Kumar   6   1   23
5     247.0          Chris Morris  15  12   13
6     229.0          Dwayne Smith  35  16    8
7     225.0         Andre Russell  10  15   15
8     217.0      Moises Henriques  15   6   12
9     203.0  Mitchell McClenaghan   2   3   17
10    203.0       Dhawal Kulkarni   2   0   18
11    201.5     Mustafizur Rahman   0   0   17
12    198.5          Dwayne Bravo  11   1   17
13    185.5        Quinton deKock  52  13    0
14    184.5        Sandeep Sharma   0   0   15
15    184.0        Ajinkya Rahane  54   9    0
16    183.5          Rohit Sharma  49  16    0
17    183.5      Yuzvendra Chahal   0   0   21
18    179.5            Axar Patel   4   8   13
19    179.5         Krunal Pandya  22  13    6
20    178.5         Praveen Kumar   4   0    9
21    175.5         Robin Uthappa  45   8    0
22    171.0          Lokesh Rahul  37  16    0
23    168.0        Shikhar Dhawan  51   8    0
24    167.0          Murali Vijay  50  10    0
25    165.5        Jasprit Bumrah   1   0   15
26    165.0          Suresh Raina  39  10    0
27    161.0          Mohit Sharma   3   1   13
28    161.0         Barinder Sran   0   0   14
29    159.0       Harbhajan Singh  11   2    9
..      ...                   ...  ..  ..  ...
129    18.5          Shreyas Iyer   2   1    0
130    18.0        Martin Guptill   3   3    0
131    17.5           Colin Munro   3   0    0
132    17.5     Rajagopal Sathish   1   1    1
133    17.0           Trent Boult   0   0    1
134    17.0       Eklavya Dwivedi   2   2    0
135    15.5         Deepak Chahar   0   0    0
136    15.0          Ishan Kishan   5   0    0
137    14.5           Travis Head   3   2    0
138    14.5          Kedar Jadhav   2   2    0
139    13.0            Adam Milne   0   0    1
140    12.0         Anureet Singh   0   0    0
141    11.5       Pradeep Sangwan   0   0    0
142    11.0        Mayank Agarwal   3   1    0
143     8.5           David Wiese   0   0    0
144     7.5     Farhaan Behardien   2   0    0
145     7.5           Nikhil Naik   1   0    0
146     6.0            Chris Lynn   0   1    0
147     5.0        Jaydev Unadkat   0   0    0
148     5.0           Aditya Tare   1   0    0
149     5.0            Dale Steyn   0   0    0
150     4.0         Shreyas Gopal   0   0    0
151     3.5         Lendl Simmons   0   1    0
152     3.0         Swapnil Singh   0   0    0
153     3.0        Sarabjit Ladda   0   0    0
154     2.5         Mandeep Singh   0   0    0
155     2.5         Akshdeep Nath   1   0    0
156     0.0          Unmukt Chand   0   0    0
157     0.0    Jagadeesha Suchith   0   0    0
158     0.0       Peter Handscomb   0   0    0

[159 rows x 5 columns]

In [10]:
a=pd1.merge(df16,df1,on='Player Name',how='outer')
a

               Player Name         Role   Base Price  points   4s   6s Wkts
0            Ishant Sharma       Bowler  2,00,00,000    52.5    0    0    3
1             Shane Watson  All-Rounder  2,00,00,000   283.0   14   12   20
2          Kevin Pietersen      Batsman  2,00,00,000    23.0    4    3    0
3             Yuvraj Singh  All-Rounder  2,00,00,000   110.0   22   13    0
4               Dale Steyn       Bowler  1,50,00,000     5.0    0    0    0
5              Aaron Finch      Batsman  1,00,00,000   158.5   45   11    0
6           Martin Guptill      Batsman    50,00,000    18.0    3    3    0
7             Dwayne Smith  All-Rounder    50,00,000   229.0   35   16    8
8           Michael Hussey      Batsman  2,00,00,000     NaN  NaN  NaN  NaN
9            Cameron White      Batsman  1,50,00,000     NaN  NaN  NaN  NaN
10      Mahela Jayawardena      Batsman  1,50,00,000     NaN  NaN  NaN  NaN
11            David Hussey      Batsman  1,00,00,000     NaN  NaN  NaN  NaN
12           Usman Khawaja      Batsman  1,00,00,000    48.0   14    3    0
13              Owais Shah      Batsman  1,00,00,000     NaN  NaN  NaN  NaN
14              Adam Voges      Batsman  1,00,00,000     NaN  NaN  NaN  NaN
15             Hashim Amla      Batsman  1,00,00,000    64.0   20    4    0
16           Rilee Rossouw      Batsman  1,00,00,000     NaN  NaN  NaN  NaN
17               Joe Burns      Batsman  1,00,00,000     NaN  NaN  NaN  NaN
18           George Bailey      Batsman  1,00,00,000    34.5    9    2    0
19   Subramaniam Badrinath      Batsman    50,00,000     NaN  NaN  NaN  NaN
20             Tamim Iqbal      Batsman    50,00,000     NaN  NaN  NaN  NaN
21          Marlon Samuels      Batsman    50,00,000     NaN  NaN  NaN  NaN
22            Richard Levi      Batsman    50,00,000     NaN  NaN  NaN  NaN
23            Darren Bravo      Batsman    50,00,000     NaN  NaN  NaN  NaN
24           Nic Maddinson      Batsman    50,00,000     NaN  NaN  NaN  NaN
25              Brad Hodge      Batsman    50,00,000     NaN  NaN  NaN  NaN
26       Cheteshwar Pujara      Batsman    50,00,000     NaN  NaN  NaN  NaN
27         Michael Klinger      Batsman    30,00,000     NaN  NaN  NaN  NaN
28          Aiden Blizzard      Batsman    30,00,000     NaN  NaN  NaN  NaN
29          Abhinav Mukund      Batsman    30,00,000     NaN  NaN  NaN  NaN
..                     ...          ...          ...     ...  ...  ...  ...
418            Eoin Morgan          NaN          NaN    41.5    8    4    0
419           Pradeep Sahu          NaN          NaN    40.5    1    1    3
420               RP Singh          NaN          NaN    39.5    0    0    3
421            Vinay Kumar          NaN          NaN    39.0    0    1    3
422         Tabraiz Shamsi          NaN          NaN    39.0    0    0    3
423         Shahbaz Nadeem          NaN          NaN    38.0    0    0    2
424          Harshal Patel          NaN          NaN    36.5    0    0    1
425         Parveez Rasool          NaN          NaN    33.0    1    0    1
426          Sarfaraz Khan          NaN          NaN    31.5    7    4    0
427       Mitchell Johnson          NaN          NaN    30.5    0    0    2
428           Ashish Reddy          NaN          NaN    30.0    2    4    1
429            Karn Sharma          NaN          NaN    30.0    3    1    0
430          Ankit Rajpoot          NaN          NaN    28.5    0    0    3
431           Albie Morkel          NaN          NaN    25.5    0    2    2
432           Ankit Sharma          NaN          NaN    23.0    0    0    1
433           Rishi Dhawan          NaN          NaN    22.5    0    1    2
434           Shreyas Iyer          NaN          NaN    18.5    2    1    0
435            Trent Boult          NaN          NaN    17.0    0    0    1
436           Kedar Jadhav          NaN          NaN    14.5    2    2    0
437             Adam Milne          NaN          NaN    13.0    0    0    1
438          Anureet Singh          NaN          NaN    12.0    0    0    0
439         Mayank Agarwal          NaN          NaN    11.0    3    1    0
440            David Wiese          NaN          NaN     8.5    0    0    0
441            Nikhil Naik          NaN          NaN     7.5    1    0    0
442             Chris Lynn          NaN          NaN     6.0    0    1    0
443          Shreyas Gopal          NaN          NaN     4.0    0    0    0
444          Lendl Simmons          NaN          NaN     3.5    0    1    0
445          Mandeep Singh          NaN          NaN     2.5    0    0    0
446           Unmukt Chand          NaN          NaN     0.0    0    0    0
447     Jagadeesha Suchith          NaN          NaN     0.0    0    0    0

[448 rows x 7 columns]

In [11]:
df3=a.sort_values(by='points',ascending=False)
df3=df3.reset_index(drop=True)
df3

                 Player Name         Role   Base Price  points   4s   6s Wkts
0                Virat Kohli          NaN          NaN   356.5   83   38    0
1               David Warner          NaN          NaN   338.5   88   31    0
2              AB deVilliers          NaN          NaN   319.5   57   37    0
3               Shane Watson  All-Rounder  2,00,00,000   283.0   14   12   20
4          Bhuvneshwar Kumar          NaN          NaN   270.0    6    1   23
5               Chris Morris          NaN          NaN   247.0   15   12   13
6               Dwayne Smith  All-Rounder    50,00,000   229.0   35   16    8
7              Andre Russell          NaN          NaN   225.0   10   15   15
8           Moises Henriques          NaN          NaN   217.0   15    6   12
9            Dhawal Kulkarni       Bowler  2,00,00,000   203.0    2    0   18
10      Mitchell McClenaghan          NaN          NaN   203.0    2    3   17
11         Mustafizur Rahman       Bowler    50,00,000   201.5    0    0   17
12              Dwayne Bravo          NaN          NaN   198.5   11    1   17
13            Quinton deKock          NaN          NaN   185.5   52   13    0
14            Sandeep Sharma          NaN          NaN   184.5    0    0   15
15            Ajinkya Rahane          NaN          NaN   184.0   54    9    0
16              Rohit Sharma  All-Rounder    10,00,000   183.5   49   16    0
17          Yuzvendra Chahal          NaN          NaN   183.5    0    0   21
18                Axar Patel          NaN          NaN   179.5    4    8   13
19             Krunal Pandya  All-Rounder    10,00,000   179.5   22   13    6
20             Praveen Kumar       Bowler    50,00,000   178.5    4    0    9
21             Robin Uthappa          NaN          NaN   175.5   45    8    0
22              Lokesh Rahul          NaN          NaN   171.0   37   16    0
23            Shikhar Dhawan          NaN          NaN   168.0   51    8    0
24              Murali Vijay          NaN          NaN   167.0   50   10    0
25            Jasprit Bumrah          NaN          NaN   165.5    1    0   15
26              Suresh Raina          NaN          NaN   165.0   39   10    0
27              Mohit Sharma       Bowler  1,50,00,000   161.0    3    1   13
28             Barinder Sran          NaN          NaN   161.0    0    0   14
29           Harbhajan Singh          NaN          NaN   159.0   11    2    9
..                       ...          ...          ...     ...  ...  ...  ...
418            Saurabh Dubey  All-Rounder    10,00,000     NaN  NaN  NaN  NaN
419           Venkatesh Iyer  All-Rounder    10,00,000     NaN  NaN  NaN  NaN
420           Mayank Siddana  All-Rounder    10,00,000     NaN  NaN  NaN  NaN
421            Shasank Singh  All-Rounder    10,00,000     NaN  NaN  NaN  NaN
422        Chandra Pal Singh  All-Rounder    10,00,000     NaN  NaN  NaN  NaN
423            Tanveer Ulhaq  All-Rounder    10,00,000     NaN  NaN  NaN  NaN
424           Iqbal Abdullah  All-Rounder    10,00,000     NaN  NaN  NaN  NaN
425          Shubham Ranjane  All-Rounder    10,00,000     NaN  NaN  NaN  NaN
426   Akhil Arvind Herwadkar  All-Rounder    10,00,000     NaN  NaN  NaN  NaN
427            Ashok Menaria  All-Rounder    10,00,000     NaN  NaN  NaN  NaN
428             Yogesh Nagar  All-Rounder    10,00,000     NaN  NaN  NaN  NaN
429             Milind Kumar  All-Rounder    10,00,000     NaN  NaN  NaN  NaN
430             Sumit Narwal  All-Rounder    10,00,000     NaN  NaN  NaN  NaN
431         Biplab Samantray  All-Rounder    10,00,000     NaN  NaN  NaN  NaN
432             Rush Kalaria  All-Rounder    10,00,000     NaN  NaN  NaN  NaN
433             Jalaj Saxena  All-Rounder    10,00,000     NaN  NaN  NaN  NaN
434            Vijay Shankar  All-Rounder    10,00,000     NaN  NaN  NaN  NaN
435     Raiphi Vincent Gomez  All-Rounder    10,00,000     NaN  NaN  NaN  NaN
436            Kuldeep Hooda  All-Rounder    10,00,000     NaN  NaN  NaN  NaN
437            Vaibhav Rawal  All-Rounder    10,00,000     NaN  NaN  NaN  NaN
438     Prasanth Padmanabhan  All-Rounder    10,00,000     NaN  NaN  NaN  NaN
439       Jaydev Gokul Bista  All-Rounder    10,00,000     NaN  NaN  NaN  NaN
440    Ankit Nagendra Sharma  All-Rounder    10,00,000     NaN  NaN  NaN  NaN
441           Kshitiz Sharma  All-Rounder    10,00,000     NaN  NaN  NaN  NaN
442          Shrikant Mundhe  All-Rounder    10,00,000     NaN  NaN  NaN  NaN
443            Abhishek Raut  All-Rounder    10,00,000     NaN  NaN  NaN  NaN
444               Rohan Prem  All-Rounder    10,00,000     NaN  NaN  NaN  NaN
445  Manjeet Kumar Chaudhary  All-Rounder    10,00,000     NaN  NaN  NaN  NaN
446            Rahul Tewatia  All-Rounder    10,00,000     NaN  NaN  NaN  NaN
447               Amit Yadav  All-Rounder    10,00,000     NaN  NaN  NaN  NaN

[448 rows x 7 columns]

In [12]:
sb1='''Shane Watson	20000000	95000000	Sold	Royal Challengers Bangalore
Pawan Negi	3000000	85000000	Sold	Delhi Daredevils
Chris Morris	5000000	70000000	Sold	Delhi Daredevils
Yuvraj Singh	20000000	70000000	Sold	Sunrisers Hyderabad
Mohit Sharma	15000000	65000000	Sold	Kings XI Punjab
Ashish Nehra	20000000	55000000	Sold	Sunrisers Hyderabad
Mitchell Marsh	20000000	48000000	Sold	Rising Pune Supergiants
Murugan Ashwin	1000000	45000000	Sold	Rising Pune Supergiants
Carlos Brathwaite	3000000	42000000	Sold	Delhi Daredevils
Sanju Samson	20000000	42000000	Sold	Delhi Daredevils
Deepak Hooda	1000000	42000000	Sold	Sunrisers Hyderabad
Karun Nair	1000000	40000000	Sold	Delhi Daredevils
Jos Buttler	15000000	38000000	Sold	Mumbai Indians
Ishant Sharma	20000000	38000000	Sold	Rising Pune Supergiants
Praveen Kumar	5000000	35000000	Sold	Rising Pune Supergiants
Kevin Pietersen	20000000	35000000	Sold	Rising Pune Supergiants
Nathu Singh	1000000	32000000	Sold	Mumbai Indians
Tim Southee	10000000	25000000	Sold	Mumbai Indians
Dwayne Smith	5000000	23000000	Sold	Gujarat Lions
Dinesh Karthik	20000000	23000000	Sold	Gujarat Lions
Dale Steyn	15000000	23000000	Sold	Gujarat Lions
Kyle Abbott	3000000	21000000	Sold	Kings XI Punjab
Krunal Pandya	1000000	20000000	Sold	Mumbai Indians
Kane Richardson	20000000	20000000	Sold	Royal Challengers Bangalore
Dhawal Kulkarni	20000000	20000000	Sold	Rising Pune Supergiants
Stuart Binny	20000000	20000000	Sold	Royal Challengers Bangalore
Rishabh Pant	1000000	19000000	Sold	Delhi Daredevils
Jaydev Unadkat	3000000	16000000	Sold	Kolkata Knight Riders
Ankit Rajpoot	1000000	15000000	Sold	Kolkata Knight Riders
John Hastings	10000000	13000000	Sold	Kolkata Knight Riders
Aditya Tare	2000000	12000000	Sold	Sunrisers Hyderabad
Brainder Sran	5000000	12000000	Sold	Sunrisers Hyderabad
Aaron Finch	10000000	10000000	Sold	Gujarat Lions
Irfan Pathan	10000000	10000000	Sold	Rising Pune Supergiants
Eklavya Dwivedi	2000000	10000000	Sold	Gujarat Lions
KC Cariappa	1000000	8000000	Sold	Kings XI Punjab
Jason Holder	5000000	7000000	Sold	Kolkata Knight Riders
Rajat Bhatia	3000000	6000000	Sold	Rising Pune Supergiants
Marcus Stoinis	3000000	5500000	Sold	Kings XI Punjab
Andrew Tye	3000000	5000000	Sold	Gujarat Lions
Travis Head	3000000	5000000	Sold	Royal Challengers Bangalore
Scott Boland	5000000	5000000	Sold	Rising Pune Supergiants
Ben Cutting	5000000	5000000	Sold	Sunrisers Hyderabad
Ashok Dinda	5000000	5000000	Sold	Royal Challengers Bangalore
Samuel Badree	5000000	5000000	Sold	Royal Challengers Bangalore
Ishan Kishan	1000000	3500000	Sold	Gujarat Lions
Vijay Shankar	1000000	3500000	Sold	Sunrisers Hyderabad
Praveen Dubey	1000000	3500000	Sold	Royal Challengers Bangalore
Peter Handscomb	3000000	3000000	Sold	Rising Pune Supergiants
Farhaan Behardien	3000000	3000000	Sold	Kings XI Punjab
Joel Paris	3000000	3000000	Sold	Delhi Daredevils
Colin Munro	3000000	3000000	Sold	Kolkata Knight Riders
Adam Zampa	3000000	3000000	Sold	Rising Pune Supergiants
RP Singh	3000000	3000000	Sold	Sunrisers Hyderabad
Sam Billings	3000000	3000000	Sold	Delhi Daredevils
Abhimanyu Mithun	3000000	3000000	Sold	Sunrisers Hyderabad
Pradeep Sangwan	2000000	2000000	Sold	Gujarat Lions
Jaydev Shah	2000000	2000000	Sold	Gujarat Lions
Shadab Jakati	2000000	2000000	Sold	Gujarat Lions
Ishwar Pandey	2000000	2000000	Sold	Rising Pune Supergiants
Pravin Tambe	1000000	2000000	Sold	Gujarat Lions
Rajagopal Sathish	2000000	2000000	Sold	Kolkata Knight Riders
Vikramjeet Malik	2000000	2000000	Sold	Royal Challengers Bangalore
Manan Sharma	1000000	1000000	Sold	Kolkata Knight Riders
Ankit Sharma	1000000	1000000	Sold	Rising Pune Supergiants
Vikas Tokas	1000000	1000000	Sold	Royal Challengers Bangalore
Akshdeep Nath	1000000	1000000	Sold	Gujarat Lions
Sarabjit Ladda	1000000	1000000	Sold	Gujarat Lions
Pardeep Sahu	1000000	1000000	Sold	Kings XI Punjab
Baba Aparajith	1000000	1000000	Sold	Rising Pune Supergiants
Chama Milind	1000000	1000000	Sold	Delhi Daredevils
Akhil Herwadkar	1000000	1000000	Sold	Delhi Daredevils
Tirumalasetti Suman	1000000	1000000	Sold	Sunrisers Hyderabad
Deepak Chahar	1000000	1000000	Sold	Rising Pune Supergiants
Jitesh Sharma	1000000	1000000	Sold	Mumbai Indians
Pratyush Singh	1000000	1000000	Sold	Delhi Daredevils
Ankush Bains	1000000	1000000	Sold	Rising Pune Supergiants
Pawan Suyal	1000000	1000000	Sold	Delhi Daredevils
Sachin Baby	1000000	1000000	Sold	Royal Challengers Bangalore
Amit Mishra	1000000	1000000	Sold	Gujarat Lions
Umang Sharma	1000000	1000000	Sold	Gujarat Lions
Jaskaran Singh	1000000	1000000	Sold	Rising Pune Supergiants
Swapnil Singh	1000000	1000000	Sold	Kings XI Punjab
Paras Dogra	1000000	1000000	Sold	Gujarat Lions
Shivil Kaushik	1000000	1000000	Sold	Gujarat Lions
Iqbal Abdulla	1000000	1000000	Sold	Royal Challengers Bangalore
Sulieman Benn	3000000	0	Unsold	
Morne Van Wyk	3000000	0	Unsold	
Brad Haddin	15000000	0	Unsold	
Johnson Charles	3000000	0	Unsold	
Ben Dunk	3000000	0	Unsold	
Cameron Bancroft	1000000	0	Unsold	
Ravi Bopara	10000000	0	Unsold	
Manoj Tiwary	10000000	0	Unsold	
Mushfiqur Rahim	3000000	0	Unsold	
Shane Dowrich	3000000	0	Unsold	
Martin Guptill	5000000	0	Unsold	
George Bailey	10000000	0	Unsold	
Hashim Amla	10000000	0	Unsold	
Subramaniam Badrinath	5000000	0	Unsold	
Mahela Jayawardene	15000000	0	Unsold	
Usman Khawaja	10000000	0	Unsold	
Michael Hussey	20000000	0	Unsold	
Tillakaratne Dilshan	15000000	0	Unsold	
Darren Sammy	5000000	0	Unsold	
Cameron Boyce	5000000	0	Unsold	
Rahul Sharma	3000000	0	Unsold	
Cheteshwar Pujara	5000000	0	Unsold	
Mithun Manhas	3000000	0	Unsold	
Pinal Shah	1000000	0	Unsold	
Rilee Rossouw	10000000	0	Unsold	
Chidhambaram Gautam	2000000	0	Unsold	
Ajantha Mendis	5000000	0	Unsold	
Michael Beer	3000000	0	Unsold	
James Pattinson	15000000	0	Unsold	
Thisara Perera	10000000	0	Unsold	
Sachithra Senanayake	5000000	0	Unsold	
Veerasammy Permaul	3000000	0	Unsold	
Devendra Bishoo	3000000	0	Unsold	
Nathan Lyon	10000000	0	Unsold	
Karanveer Singh	1000000	0	Unsold	
'''
sb=[]
sb.append(sb1.split('\n'))
pname=[]
pbase=[]
pauction=[]
for i in sb[0]:
    words=i.split('\t')
    try:
        pname.append(words[0])
        pbase.append(int(words[1]))
        pauction.append(int(words[2]))
        print(words[0],words[1],words[2])
    except IndexError:
        continue
pbase.append('')
pauction.append('')
print(len(pname))
print(len(pbase))
print(len(pauction))

Shane Watson 20000000 95000000
Pawan Negi 3000000 85000000
Chris Morris 5000000 70000000
Yuvraj Singh 20000000 70000000
Mohit Sharma 15000000 65000000
Ashish Nehra 20000000 55000000
Mitchell Marsh 20000000 48000000
Murugan Ashwin 1000000 45000000
Carlos Brathwaite 3000000 42000000
Sanju Samson 20000000 42000000
Deepak Hooda 1000000 42000000
Karun Nair 1000000 40000000
Jos Buttler 15000000 38000000
Ishant Sharma 20000000 38000000
Praveen Kumar 5000000 35000000
Kevin Pietersen 20000000 35000000
Nathu Singh 1000000 32000000
Tim Southee 10000000 25000000
Dwayne Smith 5000000 23000000
Dinesh Karthik 20000000 23000000
Dale Steyn 15000000 23000000
Kyle Abbott 3000000 21000000
Krunal Pandya 1000000 20000000
Kane Richardson 20000000 20000000
Dhawal Kulkarni 20000000 20000000
Stuart Binny 20000000 20000000
Rishabh Pant 1000000 19000000
Jaydev Unadkat 3000000 16000000
Ankit Rajpoot 1000000 15000000
John Hastings 10000000 13000000
Aditya Tare 2000000 12000000
Brainder Sran 5000000 12000000
Aaron Finch 10000000 10000000
Irfan Pathan 10000000 10000000
Eklavya Dwivedi 2000000 10000000
KC Cariappa 1000000 8000000
Jason Holder 5000000 7000000
Rajat Bhatia 3000000 6000000
Marcus Stoinis 3000000 5500000
Andrew Tye 3000000 5000000
Travis Head 3000000 5000000
Scott Boland 5000000 5000000
Ben Cutting 5000000 5000000
Ashok Dinda 5000000 5000000
Samuel Badree 5000000 5000000
Ishan Kishan 1000000 3500000
Vijay Shankar 1000000 3500000
Praveen Dubey 1000000 3500000
Peter Handscomb 3000000 3000000
Farhaan Behardien 3000000 3000000
Joel Paris 3000000 3000000
Colin Munro 3000000 3000000
Adam Zampa 3000000 3000000
RP Singh 3000000 3000000
Sam Billings 3000000 3000000
Abhimanyu Mithun 3000000 3000000
Pradeep Sangwan 2000000 2000000
Jaydev Shah 2000000 2000000
Shadab Jakati 2000000 2000000
Ishwar Pandey 2000000 2000000
Pravin Tambe 1000000 2000000
Rajagopal Sathish 2000000 2000000
Vikramjeet Malik 2000000 2000000
Manan Sharma 1000000 1000000
Ankit Sharma 1000000 1000000
Vikas Tokas 1000000 1000000
Akshdeep Nath 1000000 1000000
Sarabjit Ladda 1000000 1000000
Pardeep Sahu 1000000 1000000
Baba Aparajith 1000000 1000000
Chama Milind 1000000 1000000
Akhil Herwadkar 1000000 1000000
Tirumalasetti Suman 1000000 1000000
Deepak Chahar 1000000 1000000
Jitesh Sharma 1000000 1000000
Pratyush Singh 1000000 1000000
Ankush Bains 1000000 1000000
Pawan Suyal 1000000 1000000
Sachin Baby 1000000 1000000
Amit Mishra 1000000 1000000
Umang Sharma 1000000 1000000
Jaskaran Singh 1000000 1000000
Swapnil Singh 1000000 1000000
Paras Dogra 1000000 1000000
Shivil Kaushik 1000000 1000000
Iqbal Abdulla 1000000 1000000
Sulieman Benn 3000000 0
Morne Van Wyk 3000000 0
Brad Haddin 15000000 0
Johnson Charles 3000000 0
Ben Dunk 3000000 0
Cameron Bancroft 1000000 0
Ravi Bopara 10000000 0
Manoj Tiwary 10000000 0
Mushfiqur Rahim 3000000 0
Shane Dowrich 3000000 0
Martin Guptill 5000000 0
George Bailey 10000000 0
Hashim Amla 10000000 0
Subramaniam Badrinath 5000000 0
Mahela Jayawardene 15000000 0
Usman Khawaja 10000000 0
Michael Hussey 20000000 0
Tillakaratne Dilshan 15000000 0
Darren Sammy 5000000 0
Cameron Boyce 5000000 0
Rahul Sharma 3000000 0
Cheteshwar Pujara 5000000 0
Mithun Manhas 3000000 0
Pinal Shah 1000000 0
Rilee Rossouw 10000000 0
Chidhambaram Gautam 2000000 0
Ajantha Mendis 5000000 0
Michael Beer 3000000 0
James Pattinson 15000000 0
Thisara Perera 10000000 0
Sachithra Senanayake 5000000 0
Veerasammy Permaul 3000000 0
Devendra Bishoo 3000000 0
Nathan Lyon 10000000 0
Karanveer Singh 1000000 0
122
122
122

In [13]:
import pandas as pd2
dft=pd2.DataFrame();
dft['Player Name']=pname;
dft['Base Price']=pbase
dft['Auction Price']=pauction
dft=dft.drop(dft.index[121])
dft

               Player Name Base Price Auction Price
0             Shane Watson   20000000      95000000
1               Pawan Negi    3000000      85000000
2             Chris Morris    5000000      70000000
3             Yuvraj Singh   20000000      70000000
4             Mohit Sharma   15000000      65000000
5             Ashish Nehra   20000000      55000000
6           Mitchell Marsh   20000000      48000000
7           Murugan Ashwin    1000000      45000000
8        Carlos Brathwaite    3000000      42000000
9             Sanju Samson   20000000      42000000
10            Deepak Hooda    1000000      42000000
11              Karun Nair    1000000      40000000
12             Jos Buttler   15000000      38000000
13           Ishant Sharma   20000000      38000000
14           Praveen Kumar    5000000      35000000
15         Kevin Pietersen   20000000      35000000
16             Nathu Singh    1000000      32000000
17             Tim Southee   10000000      25000000
18            Dwayne Smith    5000000      23000000
19          Dinesh Karthik   20000000      23000000
20              Dale Steyn   15000000      23000000
21             Kyle Abbott    3000000      21000000
22           Krunal Pandya    1000000      20000000
23         Kane Richardson   20000000      20000000
24         Dhawal Kulkarni   20000000      20000000
25            Stuart Binny   20000000      20000000
26            Rishabh Pant    1000000      19000000
27          Jaydev Unadkat    3000000      16000000
28           Ankit Rajpoot    1000000      15000000
29           John Hastings   10000000      13000000
..                     ...        ...           ...
91        Cameron Bancroft    1000000             0
92             Ravi Bopara   10000000             0
93            Manoj Tiwary   10000000             0
94         Mushfiqur Rahim    3000000             0
95           Shane Dowrich    3000000             0
96          Martin Guptill    5000000             0
97           George Bailey   10000000             0
98             Hashim Amla   10000000             0
99   Subramaniam Badrinath    5000000             0
100     Mahela Jayawardene   15000000             0
101          Usman Khawaja   10000000             0
102         Michael Hussey   20000000             0
103   Tillakaratne Dilshan   15000000             0
104           Darren Sammy    5000000             0
105          Cameron Boyce    5000000             0
106           Rahul Sharma    3000000             0
107      Cheteshwar Pujara    5000000             0
108          Mithun Manhas    3000000             0
109             Pinal Shah    1000000             0
110          Rilee Rossouw   10000000             0
111    Chidhambaram Gautam    2000000             0
112         Ajantha Mendis    5000000             0
113           Michael Beer    3000000             0
114        James Pattinson   15000000             0
115         Thisara Perera   10000000             0
116   Sachithra Senanayake    5000000             0
117     Veerasammy Permaul    3000000             0
118        Devendra Bishoo    3000000             0
119            Nathan Lyon   10000000             0
120        Karanveer Singh    1000000             0

[121 rows x 3 columns]

In [14]:
b=pd2.merge(dft,df1,on='Player Name',how='outer')
b=b.sort_values('points',ascending=False)
b

               Player Name Base Price Auction Price  points   4s   6s Wkts
121            Virat Kohli        NaN           NaN   356.5   83   38    0
122           David Warner        NaN           NaN   338.5   88   31    0
123          AB deVilliers        NaN           NaN   319.5   57   37    0
0             Shane Watson   20000000      95000000   283.0   14   12   20
124      Bhuvneshwar Kumar        NaN           NaN   270.0    6    1   23
2             Chris Morris    5000000      70000000   247.0   15   12   13
18            Dwayne Smith    5000000      23000000   229.0   35   16    8
125          Andre Russell        NaN           NaN   225.0   10   15   15
126       Moises Henriques        NaN           NaN   217.0   15    6   12
24         Dhawal Kulkarni   20000000      20000000   203.0    2    0   18
127   Mitchell McClenaghan        NaN           NaN   203.0    2    3   17
128      Mustafizur Rahman        NaN           NaN   201.5    0    0   17
129           Dwayne Bravo        NaN           NaN   198.5   11    1   17
130         Quinton deKock        NaN           NaN   185.5   52   13    0
131         Sandeep Sharma        NaN           NaN   184.5    0    0   15
132         Ajinkya Rahane        NaN           NaN   184.0   54    9    0
133           Rohit Sharma        NaN           NaN   183.5   49   16    0
134       Yuzvendra Chahal        NaN           NaN   183.5    0    0   21
22           Krunal Pandya    1000000      20000000   179.5   22   13    6
135             Axar Patel        NaN           NaN   179.5    4    8   13
14           Praveen Kumar    5000000      35000000   178.5    4    0    9
136          Robin Uthappa        NaN           NaN   175.5   45    8    0
137           Lokesh Rahul        NaN           NaN   171.0   37   16    0
138         Shikhar Dhawan        NaN           NaN   168.0   51    8    0
139           Murali Vijay        NaN           NaN   167.0   50   10    0
140         Jasprit Bumrah        NaN           NaN   165.5    1    0   15
141           Suresh Raina        NaN           NaN   165.0   39   10    0
142          Barinder Sran        NaN           NaN   161.0    0    0   14
4             Mohit Sharma   15000000      65000000   161.0    3    1   13
143        Harbhajan Singh        NaN           NaN   159.0   11    2    9
..                     ...        ...           ...     ...  ...  ...  ...
86           Sulieman Benn    3000000             0     NaN  NaN  NaN  NaN
87           Morne Van Wyk    3000000             0     NaN  NaN  NaN  NaN
88             Brad Haddin   15000000             0     NaN  NaN  NaN  NaN
89         Johnson Charles    3000000             0     NaN  NaN  NaN  NaN
90                Ben Dunk    3000000             0     NaN  NaN  NaN  NaN
91        Cameron Bancroft    1000000             0     NaN  NaN  NaN  NaN
92             Ravi Bopara   10000000             0     NaN  NaN  NaN  NaN
93            Manoj Tiwary   10000000             0     NaN  NaN  NaN  NaN
94         Mushfiqur Rahim    3000000             0     NaN  NaN  NaN  NaN
95           Shane Dowrich    3000000             0     NaN  NaN  NaN  NaN
99   Subramaniam Badrinath    5000000             0     NaN  NaN  NaN  NaN
100     Mahela Jayawardene   15000000             0     NaN  NaN  NaN  NaN
102         Michael Hussey   20000000             0     NaN  NaN  NaN  NaN
103   Tillakaratne Dilshan   15000000             0     NaN  NaN  NaN  NaN
104           Darren Sammy    5000000             0     NaN  NaN  NaN  NaN
105          Cameron Boyce    5000000             0     NaN  NaN  NaN  NaN
106           Rahul Sharma    3000000             0     NaN  NaN  NaN  NaN
107      Cheteshwar Pujara    5000000             0     NaN  NaN  NaN  NaN
108          Mithun Manhas    3000000             0     NaN  NaN  NaN  NaN
109             Pinal Shah    1000000             0     NaN  NaN  NaN  NaN
110          Rilee Rossouw   10000000             0     NaN  NaN  NaN  NaN
111    Chidhambaram Gautam    2000000             0     NaN  NaN  NaN  NaN
112         Ajantha Mendis    5000000             0     NaN  NaN  NaN  NaN
113           Michael Beer    3000000             0     NaN  NaN  NaN  NaN
114        James Pattinson   15000000             0     NaN  NaN  NaN  NaN
116   Sachithra Senanayake    5000000             0     NaN  NaN  NaN  NaN
117     Veerasammy Permaul    3000000             0     NaN  NaN  NaN  NaN
118        Devendra Bishoo    3000000             0     NaN  NaN  NaN  NaN
119            Nathan Lyon   10000000             0     NaN  NaN  NaN  NaN
120        Karanveer Singh    1000000             0     NaN  NaN  NaN  NaN

[214 rows x 7 columns]

In [15]:
namenan=[]
for index,row in b.iterrows():
    if row['Base Price']==-1:
        namenan.append(row['Player Name'])
print(namenan)
print(len(namenan))

[]
0

In [16]:
%store b

Stored 'b' (DataFrame)

In [ ]:
b[]